In [ ]:
import pandas as pd

In [ ]:
a=pd.read_csv('/content/SOCR-HeightWeight.csv')
a.head(10)

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971
5      6        68.69784        123.3024
6      7        69.80204        141.4947
7      8        70.01472        136.4623
8      9        67.90265        112.3723
9     10        66.78236        120.6672

In [ ]:
x=a[["Height(Inches)"]]
y=a[["Weight(Pounds)"]]

In [ ]:
print(f'Null values: {a.isnull().sum().sum()}')
a.isnull().any()

Null values: 0

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

       Height(Inches)
3681         68.37014
16937        66.87820
22327        68.73289
11888        70.97371
4492         68.12126
...               ...
8185         68.93408
23710        67.74268
3619         64.50981
1511         65.40895
10073        68.01553

[20000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

7.88236682761877

In [ ]:
mean_squared_error(y_test,y_pred)

97.99446067105455

In [ ]:
r2_score(y_test,y_pred)

0.2608293076625334

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"Linear.pkl")

['Linear.pkl']

Pyspark Big Data

In [ ]:
!pip install pyspark --quiet
print('Installed')

Installed

In [ ]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.functions import year,month,to_date,col,round as spark_round

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
spark=SparkSession.builder.appName('Day4_BigData_Sales').config('spark.sql.adaptive.enabled','true').getOrCreate()

print(f'spark Session :{spark.version}')
print(f'SparkSession :ACTIVE')
print(f'Application :{spark.sparkContext.appName}')

spark Session :4.0.2
SparkSession :ACTIVE
Application :Day4_BigData_Sales